version: '3'
services:
  db:
    image: mysql:5.6.39
    networks:
      - lok-vacha

    environment:
      - MYSQL_DATABASE=lokvacha
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
  s3proxy:
    image: andrewgaul/s3proxy
    networks:
      - lok-vacha
    environment:
      - S3PROXY_AUTHORIZATION=none
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    environment:
      - SERVER_CONFIG_PATH=/code/docker/local-docker-config.json
    networks:
      - lok-vacha
    ports:
      - 9001:9000
    command: bash -c "/code/docker/prepare_s3.sh && yarn && yarn start"

networks:
  lok-vacha:
